# Generated by Django 2.1.4 on 2019-01-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_session_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='row_number',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
    ]
