# Generated by Django 2.1.4 on 2019-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20190113_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='column_number',
            field=models.IntegerField(null=True),
        ),
    ]
