# Generated by Django 2.1.4 on 2019-01-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('restapi', '0004_auto_20190113_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete='cascade', to='user.Profile'),
        ),
    ]
