# Generated by Django 2.1.4 on 2019-01-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='clicked_on_label_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='has_tsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_labeled_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_variable_groups',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='row_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tsm_bound',
            field=models.FloatField(null=True),
        ),
    ]
