# Generated by Django 2.1.4 on 2019-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20190122_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='classifier',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='learner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
