package machinelearning.active.learning.versionspace.convexbody.sampling;

import machinelearning.active.learning.versionspace.convexbody.ConvexBody;

/**
 * This interface is a Factory for creating the appropriate {@link DirectionSampler} used by the {@link HitAndRunSampler}.
 * This algorithm choice can have a profound impact on the mixing time of the Markov Chain generated by the Hit-and-Run algorithm.
 * For example, the {@link RoundingAlgorithm} is better suited for cases when the convex body is very thin or elongated
 * along some directions (and more time consuming), while the usual {@link RandomDirectionSampler} can perform poorly in these cases
 * (but it is fast).
 *
 * @see HitAndRunSampler
 * @see RandomDirectionSampler
 * @see EllipsoidSampler
 */
public interface DirectionSamplingAlgorithm {
    /**
     * @param body: convex body used for fitting the {@link DirectionSampler} technique
     * @return a direction sampling algorithm which samples directions in a fashion targeted to this specific convex body
     */
    DirectionSampler fit(ConvexBody body);
}
